# Generated by Django 3.1.3 on 2020-11-30 14:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='defult.jpg', upload_to=users.models.Profile.make_user_dir),
        ),
    ]
